### ISSUE TITLE
Define DELETE to allow for marking objects for deletion.  Administrator must approve.

### ISSUE THREAD

**Issue by carmstrong1gw** [biocompute-objects/bco_api#10]

**Comment by HadleyKing** [comment]
@syntheticgio 
Any opinions or ideas about this?

**Comment by syntheticgio** [comment]
It’s possible to add this, we would need to create an admin panel. Might be worth the effort for this and other administrative features though.

**Comment by HadleyKing** [comment]
[dfb981b](https://github.com/biocompute-objects/portal/pull/128/commits/dfb981be31b01f9cdaec2b0449df074efcc2e75a)

New function for delete button on portal submits the value `status: "DELETE"` for the BCO, making it invisible/inaccessible via UI

Goes with f6c362666c6370f86e64d622eb2a9071e29a90c0 from `bco_api`
