### ISSUE TITLE
The "Open Portal in new tab" button is not responsive. 

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_api#113]
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/23385872/157273291-3387c7d6-37e4-4003-955c-e30a807df9fa.png">

The "Open Portal in new tab" button is not responsive. 

`Failed to load resource: the server responded with a status of 424 (Failed Dependency)`
[Inspect](https://biocomputeobject.org/api/accounts/activate/janishapatel%40gwu.edu/4307e818ec364d1db16b51046c42ee64
)

**Comment by HadleyKing** [comment]
743a7c5c040697449dd088e6ff66c0d295d7a70e
