### ISSUE TITLE
Add Additional tools to the BCO API.

### ISSUE THREAD

**Issue by carmstrong1gw** [biocompute-objects/bco_api#12]
This would be tools in the https://github.com/biocompute-objects/bcotool repo.

**Comment by HadleyKing** [comment]
This is the https://github.com/biocompute-objects/bcotool repo.

**Comment by HadleyKing** [comment]
@rajamazumder has requested this be moved to `critical` for the next release [22.02](https://github.com/biocompute-objects/bco_api/milestone/3)
