### ISSUE TITLE
Validate draft

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/bco_api#139]
# **Describe the bug**
*For 22.06 testing. Unable to validate draft .*

# **To Reproduce**
For a BCO draft, after editing and saving the current draft. 
1. Click on 'SAVE CURRENT DRAFT'
2. Select Display Validation
3. Click on 'VALIDATE DRAFT'
4. See Error message: Save Draft Failed! Error:500

# **Screenshots**
![Screen Shot 2022-06-21 at 16 53 27](https://user-images.githubusercontent.com/90009613/174895430-ea705626-9e13-4e10-b69e-34de5362d20c.png)

***[PASTE IMAGE HERE. OPTIONALLY ADD DESCRIPTION]***

# **Desktop (please complete the following information):**

MacOS Monterey - Firefox

**Comment by HadleyKing** [comment]
This was an SELinux issue on the server, and not related to the code. It has been resolved.
