### ISSUE TITLE
Develop tests and document '/api/accounts/describe/'

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#168]

**Comment by Reeya123** [comment]
Hi @HadleyKing 
Please check the test file for api_accounts_describe api.

- As per our discussion, I changed the format of the Authorization token in the request header of the test by adding a "Token" Keyword. 
- The test still gave a 403 forbidden request
- I learned that Django requires CSRF protection for POST requests, and without the CSRF token, the requests may be blocked, leading to a status code of 403.
- So in the code I retrieve the CSRF token from the test client's cookies and use it in request body only if it can be retrieved. I keep receiving CSRF token not found error.
- Might use Force login method but unsure if I should go ahead with this.
**- Please take a look when you get chance.**
Attaching ss and pull request
<img width="574" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/50a0c48a-77b4-4f1c-ae81-14f9fc3c3082">


Error:

<img width="436" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/f5709aa2-9bcb-44f6-8fae-482c23cc633b">



**Command to run it: python -m pytest tests/test_views/test_api_accounts_describe.py**

**Comment by Reeya123** [comment]
Expected response codes for endpoint api/accounts/describe/ on Swagger documentation:
<img width="370" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/759a5ad2-a0ee-4693-ba76-2a1a16ecffb6">


After testing,
expected response: 200 (successful Response)
received response: 200 (Successful Response)

**_expected response: 400 (Bad request)
received response: 403 (Forbidden)_**

**_expected response: 401 (Unauthorized: Authentication credentials were not provided)
received response: 403 (Forbidden)_**

Update Swagger documentation

**Comment by HadleyKing** [comment]
65591f7bb340f9d60d1744fdbb606ae2d24437fe
