### ISSUE TITLE
Develop tests and document '/api/auth/add/'

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#169]

**Comment by Reeya123** [comment]
Expected response codes for endpoint  `api/auth/add/` on Swagger documentation: 
<img width="335" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/d56e9bee-1759-41ca-ba86-2f27c2c710e8">


After testing, 
**_expected response: 200 (successful request)
received response: 201 (Created)_**

expected response: 201 (Created)
received response: 201 (Created)

expected response: 400 (Bad request)
received response: 400 (Bad Request)

_**expected response: 409 (Conflict - Object already exists for the account)
received response: 201 (Created)**_

Update Swagger documentation
