### ISSUE TITLE
Develop tests and document '/api/auth/remove/'

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#170]

**Comment by Reeya123** [comment]
Expected response codes for endpoint api/auth/add/ on Swagger documentation:
<img width="386" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/a38cf5c2-5def-42db-b277-f44546d81ce7">

After testing,
**_expected response: 200 (successful request)
received response: 409 (Conflict - Object already exists for the account)_**

expected response: 400 (Bad request)
received response: 400 (Bad Request)

expected response: 409 (Conflict - Object already exists for the account)
received response: 409 (Conflict - Object already exists for the account)

Update Swagger documentation

**Comment by Reeya123** [comment]
Branch for auth_remove created
