### ISSUE TITLE
Develop tests and document '/api/objects/?contents='

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#174]
[searchBcodbAPI](http://localhost:8000/api/docs/#/BCO%20Management/api_objects_list)

**Comment by Reeya123** [comment]
Swagger documentation missing. Unable to test at this time.

**Comment by Reeya123** [comment]
https://biocomputeobject.org/api/docs/#/Account%20Management/api_objects_list

**Comment by HadleyKing** [comment]
9c2768fae27875714923fcd7ffbf7f4ba1a96492

**Comment by HadleyKing** [comment]
https://github.com/biocompute-objects/bco_api/pull/248
