### ISSUE TITLE
Develop tests and document '/api/objects/search/'

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#175]

**Comment by Reeya123** [comment]
Expected response codes for endpoint api/objects/search on Swagger documentation:
<img width="331" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/31343c6b-bc1f-4655-8d2b-455b248c1b1b">

After testing,
**_expected response: 200 (successful request)
received response: 404 (Not Found)_**

expected response: 404 (Not Found)
received response: 404 (Not Found)

Update Swagger documentation

**Comment by Reeya123** [comment]
Merged to 23.09
