### ISSUE TITLE
Develop tests and document '/api/groups/group_info/'

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#176]

**Comment by Reeya123** [comment]
**Documentation needs to be updated. Add an example case**
<img width="593" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/907403cf-d989-40bd-8317-561ae7535062">

**Comment by Reeya123** [comment]
Expected response codes for endpoint api/auth/add/ on Swagger documentation:
<img width="470" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/62ca3261-d894-4460-b938-ecb9c714c254">

After testing,
expected response: 200 (Authorization is successful)
received response: 200 (Authorization is successful)

**expected response: 400 (Bad request)
received response: 403 (Forbidden Request)

expected response: 401 (Unauthorized: Authentication credentials were not valid)
received response: 403 (Forbidden Request)**

Update Swagger documentation
