### ISSUE TITLE
Develop tests and document '/api/prefixes/token/'

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#177]

**Comment by Reeya123** [comment]
Expected response codes for endpoint api/prefixes/token/ on Swagger documentation:
<img width="553" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/436d6f4c-647c-4c0c-b86a-89c8616ff6fb">


After testing,
expected response: 200 (successful Response)
received response: 200 (Successful Response)

**_expected response: 400 (Bad request)
received response: 403 (Forbidden)_**

Update Swagger documentation
