### ISSUE TITLE
Develop tests and document '/api/objects/drafts/publish/'

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#181]

**Comment by Reeya123** [comment]
**Update the documentation. Add an example case for reference** 

<img width="574" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/5be233c5-a6b9-415c-a49f-ad84c8f36a52">

**Comment by Reeya123** [comment]
Expected response codes for endpoint api/objects/drafts/publish// on Swagger documentation:
<img width="929" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/87b71912-70c9-44ff-a5d4-d23a2898519c">


After testing,
**_expected response: 200 (successful Response)
received response: 207 (Multi-status)_**

**_expected response: 400 (Bad request)
received response: 207 (Multi-status)_**

**_expected response: 300 (Some Requests failed)
received response: 207 (Multi-status)_**

expected response: 403 (Invalid Token)
received response: 403 (Invalid Token)

Update Swagger documentation

**Comment by HadleyKing** [comment]
@Reeya123 
See https://github.com/biocompute-objects/bco_api/pull/220#:~:text=UPdated%20Swagger%20Docs%20for%20objects_draft_publish 
I updated the Swagger docs and the response codes from the API script to match. Let me know if you have trouble with the tests now.

**Comment by Reeya123** [comment]
@HadleyKing 
Receiving 403(Insufficient permissions) instead of 200, 400, 300

**Comment by Reeya123** [comment]
Merged to 23.09
