### ISSUE TITLE
Develop tests and document '/api/groups/modify/'

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#183]

**Comment by Reeya123** [comment]
**Expected response codes for endpoint api/groups/modify/ on Swagger documentation:**
<img width="431" alt="image" src="https://github.com/biocompute-objects/bco_api/assets/56750374/c35ec536-1736-4f9f-83e7-eb97b4a8c5fe">


After testing,
expected response: 200 (successful group modification)
received response: 200 (successful group modification)

**_expected response: 400 (Bad request)
received response: 200 (successful group modification)_**

expected response: 403 (Insufficient privileges)
received response: 403 (Insufficient privileges)

Update Swagger documentation
