### ISSUE TITLE
Develop a test DB that can be applied using Django and pytest Fixtures

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#184]
- [x] #185
- [x] #186

**Comment by Reeya123** [comment]
## Update on task: July 7th, 23

### Week 2 task: Use the small database(bcodb) provided in the BCO API GitHub repository for learning about databases in pytest unit testing and also write unit tests.

- spent a few hours learning from the resources available on the internet to get knowledge about tackling databases in unit testing

- Wrote a test to ensure that the default database engine is set to SQLite3, as specified in the DATABASES setting. 

  This test  helps in verifying the correct configuration of the database engine. The test passed asserting the databse engine is 
  set to sqlite3

- wrote a test to check if the database is properly configured and a connection can be established. 

  This test helps in identifying any issue with the database configuration and connection.

- wrote a test to verify that the database name is correctly set in the NAME setting of the DATABASES configuration. 

  Asserted  that the value of settings.DATABASES['default']['NAME'] is not empty or None.

- wrote tests ofr APIs associated with specific URLs in the urls.py file. 

  Made use of Django's test framework and the Client class to simulate requests and make assertions on the responses.

- working on a Test to check database models and migrations. the tests will check that the models are correctly defined and can be used to create database tables

Will go over this progress in the Monday Scrum meeting on July 10.

**Comment by Reeya123** [comment]
## Week 3 tasks
### Task: Export the database as a pytest fixture that can be used for testing.

Created a pull request. Waiting for review @HadleyKing 
https://github.com/biocompute-objects/bco_api/pull/192
