### ISSUE TITLE
Utilize pytest fixtures to create reusable test setup code for the BCO API tests, enhancing test organization and efficiency.

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#185]
- https://realpython.com/testing-in-django-part-1-best-practices-and-examples/
- https://realpython.com/testing-in-django-part-2-model-mommy-vs-django-testing-fixtures/

**Comment by Reeya123** [comment]
@HadleyKing . I have completed reviewing them. Finishing the three tutorials was week 1 task that has been completed. I can take more time and review other django pytest resources/tutorials to gain more understanding or can take up a new task. Whatever you suggest
