### ISSUE TITLE
Follow the third tutorial on "Django and pytest Fixtures" to deepen your understanding of pytest fixtures and how they can be applied in Django testing.

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#186]
https://realpython.com/django-pytest-fixtures/

**Comment by Reeya123** [comment]
## Update on this task - Wednesday, June 28
Have total 3 tutorials:

Completed tutorial 1: How to Provide Test Fixtures for Django Models in Pytest
I learned: 
- How to create and load test fixtures in Django
- How to create and load pytest fixtures for Django models
- How to use factories to create test fixtures for Django models in pytest

Completed 50% of tutorial 2: Testing in Django: Best practices and examples
- Going through examples of good unit tests

**Comment by Reeya123** [comment]
The three tutorials have been completed. This marks end of week 1 tasks.
