### ISSUE TITLE
API for modifying draft BCO

### ISSUE THREAD

**Issue by rykahsay** [biocompute-objects/bco_api#209]
Can you give me an example API call that updates existing draft GLY_** BCO? For example, Jeet wants me to update "extension_schema" for all GlyGen draft BCO:

=========
From:
“extension_schema”: “http://www.w3id.org/biocompute/extension_domain/1.2.0/dataset/dataset_extension.json”,

To:
“extension_schema”: “https://www.w3id.org/biocompute/extension_domain/1.2.0/dataset/dataset_extension.json”,

**Comment by HadleyKing** [comment]
@rykahsay 
The browsers were throwing CORS issues for going from HTTP to HTTPS. I added a condition that would automatically do the conversion

**Comment by HadleyKing** [comment]
But to do what you are asking would have to be done either with a SQL command on the server or a dump to replace all the BCOs.
