### ISSUE TITLE
Create script to manually set object versioning numbers

### ISSUE THREAD

**Issue by carmstrong1gw** [biocompute-objects/bco_api#22]
Right now we don't have a way to set object versioning numbers in the api using metafixtures.json.  Someone needs to create a script to allow 1) the existing numbers to be pulled, and 2) to update a new installation of the API.  This is related to creating object backups as well, which is already done in cag.sh.

**Comment by jpat1546** [comment]
relates to #37

**Comment by HadleyKing** [comment]
@syntheticgio Maybe this is possible for the 22.01 release? 
I think once #57 is cleared we can discuss this one.
