### ISSUE TITLE
Referenced in Publication

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#24]
add meta tag `Referenced in Publication`

**Comment by HadleyKing** [comment]
This would be an additional field added to the Model.bco to indicate if A BCO was referenced in a PEER REVIEWED publication, and as such should be public and available.

**Comment by HadleyKing** [comment]
Can repurpose the `Status` field in the BCO model

**Comment by jpat1546** [comment]
External references & usability domain: This object has been created based on a workflow in x publication from Janisha Patel to Everyone:    

 BCO tag _:Referenced in Publication:_  A publication has referenced this object
