### ISSUE TITLE
Push to Sandbox BCODB Site

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/bco_api#267]
Email from Sam:

> Hey Jonathon, Hadley,

> Can I get clarification on a question that came up as we're reviewing the latest BCOnexus image?  
> 
> In https://github.com/biocompute-objects/dnanexus/issues/2 in the screenshot, it looks like Hadley is pushing a BCO to a database running on local (localhost).  We've built the BCOnexus app to submit to the public BCODB on the BioCompute Portal, but we didn't configure it for pushing to local hosts; in all of our testing, we used the sandbox BCODB.
> 
> Could you try pushing to the sandbox BCODB site instead and confirm that works?
> 
> Best,
> Sam

**Comment by HadleyKing** [comment]
Done. Request inside of the Docker succeeds but no BCO makes it to the DB. The error is still on their end.
