### ISSUE TITLE
updateDraftBCO: `${bcoURL}objects/drafts/modify/`, {"POST_api_objects_drafts_modify"...}

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#302]

**Comment by tiwa1154** [comment]
[Swagger](https://biocomputeobject.org/api/docs/#/BCO%20Management/api_objects_drafts_modify_create) exists and executable tryout

**Comment by tiwa1154** [comment]
Committed to Github `39080443e40a09c7c015105abd9201e5cc1ceeec`
