### ISSUE TITLE
publishDraftBCO: `${bcoURL}objects/drafts/publish/`, {"POST_api_objects_drafts_publish"...}

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#303]

**Comment by tiwa1154** [comment]
[Swagger](https://biocomputeobject.org/api/docs/#/BCO%20Management/api_objects_drafts_publish_create) exists with excutable tryout.

**Comment by tiwa1154** [comment]
Needs API test script

**Comment by tiwa1154** [comment]
Issue: showing 300 code instead of 207

**Comment by tiwa1154** [comment]
Kicked back to Hadley for further investigation
