### ISSUE TITLE
Provide a curated list of quality BCOs for example

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#312]
We need a list of BCOs that can fulfill two main functions:
- [ ] Exemplar BCOs referenced in publications
- [ ] BCOs that have important features for testing to be included in the example DB 

@tiwa1154 I want to use the table below to track this issue

| | BCO ID | BCO Name | Reason for picking | URL In Publication | Publication URL is working |
|-|--------|------------|--------------------|--------------------|---------------------------|
|||||||||
| 1. | https://biocomputeobject.org/viewer?https://biocomputeobject.org/BCO_000038/1.0 | R Safety Assessment Algorithm for Aluminum in Infant Vaccines | Algorithm developed by CBER and has associated publication | NA | Yes |
| 2. | https://biocomputeobject.org/viewer?https://biocomputeobject.org/BCO_000452/1.0 | WGS Simulation of DUF1220 Regions | Seems to be a more complete BCO with good provenance and usability domain, and execution and error domain.  | NA | Yes |
| 3. | Figshare | RNA-Seq Differential Expression & Pathway Analysis | Referenced in https://f1000research.com/articles/9-1144/v1 | No | |
| 4. |https://biocomputeobject.org/viewer?https://biocomputeobject.org/BCO_069535/1.0 | Merck RVDB (v18) Curation Pipeline | Referenced in https://www.sciencedirect.com/science/article/pii/S1359644624000096?via%3Dihub#s0060. v2.0 is also available | ||
| 5. | https://biocomputeobject.org/viewer?https://biocomputeobject.org/BCO_031929/1.0 | In-silico viral reads generation from Human Adenovirus, West Nile virus, Hepatitis B virus, and Lassa virus sequences. | Referenced in https://www.sciencedirect.com/science/article/pii/S1359644624000096?via%3Dihub#s0060. | ||
| 6. | Couldn't find in BCODB, S3 file | Viral metagenomic analysis using the lenient alignment settings | Referenced in https://www.sciencedirect.com/science/article/pii/S1359644624000096?via%3Dihub#s0060.  | ||
| 7. | Couldn't find in BCODB, S4 file | Viral metagenomics analysis using the stringent alignment settings | Referenced in https://www.sciencedirect.com/science/article/pii/S1359644624000096?via%3Dihub#s0060.  Some BCOs were mentioned in this article Table 2 but not exist in BCODB | ||
| 8. | https://biocomputeobject.org/viewer?https://biocomputeobject.org/BCO_000062/1.0 | HCV1a ledipasvir resistance SNP detectio | Referenced in https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000099#sec013 | ||

**Comment by ChinweokeO** [comment]
- BCOs that have been referenced in a publication
- duf1220 domain of unknown function, copy number variation
- cwl: https://github.com/biocompute-objects/bcotool/blob/main/data_tests/collapsed-cwl-blastn-homologs.json
- gdc pipeline
- neoantigen pipeline**

**Comment by kee007ney** [comment]
CWL example (not yet published in the Portal): https://biocomputeobject.org/builder?https%3A%2F%2Fbiocomputeobject.org%2FDNAN_000009%2FDRAFT=

**Comment by tiwa1154** [comment]
Outcome: default search shows curated list of BCOs

**Comment by tiwa1154** [comment]
I have created a SP for the list of BCOs: https://gwu0.sharepoint.com/sites/BioCompute-GRP/_layouts/15/doc.aspx?sourcedoc={09f5ed86-3813-4f7e-af25-9a6244bcaefa}&action=edit

**Comment by HadleyKing** [comment]
@tiwa1154 

can you add these two bcos to that list:
- [ ] [https://biocomputeobject.org/BCO_022530/2.2](https://biocomputeobject.org/viewer?https://biocomputeobject.org/BCO_022530/2.2)
- [ ] [https://biocomputeobject.org/BCO_022531/2.2](https://biocomputeobject.org/viewer?https://biocomputeobject.org/BCO_022531/2.2)

**Comment by kee007ney** [comment]
Please add this BCO to the list, then we can close the ticket.
https://biocomputeobject.org/viewer?https://biocomputeobject.org/BCO_095545/1.2
@HadleyKing
