### ISSUE TITLE
Propose ideas for BCO ranking system (Phase II)

### ISSUE THREAD

**Issue by ChinweokeO** [biocompute-objects/bco_api#328]

**Comment by Kirans0615** [comment]
BCO Ranking Based on BCO Builder
-Provenance Domain: 
        a. 1 Point if name, version, license, derived from and created/modified inserted and verified
        b. 1 Point if Obsolete Date and Embargo and Filled
        c. 1 Point if at least 3 Contributors are added
        d. 1 Point if Review is inserted and verified
-Usability Domain:
        a. 1 Point if 3 usability domain are filled
-Description Domain: 
        a. 1 point if 3 keywords are given and verified
        b. 1 point if all needed platforms are inserted (verified through repo)
-Extension Domain:
       a. 2 Points if extension domain if filled out in its entirety
-Parametric Domain:
       a. 1 Point if 3 steps are added and verified
-I/O Domain:
       a.  1 Point for each pair of input and output subdomain added and verified
-Execution Domain:
       a. 1 Point if a verified script driver is added
       b. 1 Point for each Script added with a verified prerequisite
       c. 1 Point for each external data endpoint verified with the repo 
-Error Domain:
       a. 2 Points if both algorithmic and empirical error and filled correctly and verified with the repo

Anything with >20 points is considered the highest ranking BCO

**Comment by kee007ney** [comment]
@Kirans0615 Have you started implementing any scoring rules?
