### ISSUE TITLE
Integrate Comparator

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/bco_api#335]
Integrate either Sean Keeney's or Sean Kim's comparator tool into Portal, create an API endpoint to call.

**Comment by kee007ney** [comment]
According to @seankim658, correcting the output should be as simple as a json.load call. Once done, can push to prd.

**Comment by seankim658** [comment]
Small correction, should be a `json.loads` call. But that *should* be all you need to serialize the valid JSON string to a Python dictionary which can then be returned as part of the response object.
