### ISSUE TITLE
No sample BCOs bootstrapped in DB

### ISSUE THREAD

**Issue by syntheticgio** [biocompute-objects/bco_api#41]
**Describe the bug**
Doesn't appear to have any sample BCO bootstrapped in the DB.  Is there another loaddata that we can run to get these?  Or can this be added?

**Comment by syntheticgio** [comment]
This is a bit of a barrier for testing, since it is difficult to properly create a BCO by hand (and not sure the builder page is working - doesn't appear to right now for me to anything more than create a draft)

**Comment by HadleyKing** [comment]
https://github.com/biocompute-objects/bco_api/commit/15fcf58bec65bf19100a840155410fa42731216d
