### ISSUE TITLE
Update Best Practices to recommend that previous versions do not change

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/bco_api#73]
Need something in best practices to make it clear that any version previous to the current version of a BCO not be edited. Temporary solution until a software feature change is implemented.

**Comment by jpat1546** [comment]
https://github.com/biocompute-objects/BCO_Specification/commit/0782a6a0e60f29ff1c442cfb7a27ec12e2271dbc

**Comment by jpat1546** [comment]
https://github.com/biocompute-objects/BCO_Specification/commit/15d30412d5faa86694d27d91a9ee0f3ee2b73384

**Comment by jpat1546** [comment]
[1761385](https://github.com/biocompute-objects/BCO_Specification/commit/176138585793d139301d1034e6758e04f0635e3f)
