### ISSUE TITLE
Define GET to allow retrieval of all objects or a selected object.  Should allow for retreiving only object IDs.

### ISSUE THREAD

**Issue by carmstrong1gw** [biocompute-objects/bco_api#9]

**Comment by jpat1546** [comment]
relates to #37 #22 
Will be either
- solved by one of the above issues OR
- easy addition once #37  are resolved

**Comment by HadleyKing** [comment]
related to #23

**Comment by HadleyKing** [comment]
#23 addresses the unfinished part of this issue.
